# Generated by Django 3.0.4 on 2020-03-29 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dateRegistration',
        ),
        migrations.RemoveField(
            model_name='company',
            name='masterId',
        ),
        migrations.AddField(
            model_name='company',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
