# Generated by Django 3.0.4 on 2020-03-29 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20200329_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dateCreated',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='dateRegistration',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
