# Generated by Django 3.0.4 on 2020-04-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_companynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='Company.Company'),
        ),
    ]
