# Generated by Django 3.1.2 on 2020-10-08 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0012_auto_20201009_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
