# Generated by Django 3.1.2 on 2020-10-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_auto_20201009_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/companies/logo/'),
        ),
    ]
