# Generated by Django 3.1.2 on 2020-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_auto_20201010_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(default='{"coords": {"latitude": 0.0, "longitude": 0.0}, "country": "", "adress": ""}'),
        ),
    ]
