# Generated by Django 3.0.4 on 2020-03-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20200329_1604'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='companyId',
        ),
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Company.Company'),
            preserve_default=False,
        ),
    ]
