# Generated by Django 3.0.4 on 2020-03-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_auto_20200331_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dateCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='dateRegistration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
