# Generated by Django 3.0.4 on 2020-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_auto_20200331_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
