# Generated by Django 3.0.4 on 2020-03-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_service_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
