# Generated by Django 3.1.2 on 2020-10-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_auto_20200331_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='typeId',
        ),
    ]
