# Generated by Django 3.1.2 on 2020-10-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_remove_service_typeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wednesday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
                ('saturday', models.CharField(max_length=255)),
                ('sunday', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='Service.ServiceType'),
        ),
        migrations.AddField(
            model_name='service',
            name='workSchedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workSchedule', to='Service.workschedule'),
        ),
    ]
