# Generated by Django 3.1.2 on 2020-10-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_auto_20201010_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='friday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='monday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='saturday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='sunday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='thursday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='tuesday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='wednesday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
