# Generated by Django 3.1.2 on 2020-10-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_auto_20201010_2147'),
        ('Service', '0014_auto_20201010_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
