# Generated by Django 3.1.2 on 2020-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0015_auto_20201010_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
