# Generated by Django 3.1.2 on 2020-10-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0017_auto_20201010_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='service',
            name='country',
        ),
    ]
