# Generated by Django 3.1.2 on 2020-10-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0019_auto_20201011_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='user',
            new_name='master',
        ),
    ]
