# Generated by Django 3.0.4 on 2020-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='endDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
