# Generated by Django 3.0.4 on 2020-04-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_auto_20200418_1119'),
        ('Workers', '0004_auto_20200418_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='Department.Department'),
        ),
    ]
