# Generated by Django 3.0.4 on 2020-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0005_auto_20200418_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='endDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
