# Generated by Django 3.0.4 on 2020-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0006_auto_20200418_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
