# Generated by Django 3.0.4 on 2020-04-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Position', '0001_initial'),
        ('Workers', '0007_auto_20200418_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhistory',
            name='department',
        ),
        migrations.AddField(
            model_name='workhistory',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='Position.Position'),
        ),
    ]
